version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
matrix:
  exclude:
    - node_js: "12.17"
      env: TEST=true ALLOW_FAILURE=true
  include:
    - node_js: "14.14" # first 14.x with patterns
      env: TEST=true
    - node_js: "12.17" # first 12.x with ESM
      env: TEST=true
    - node_js: "12.16.0" # this node version incorrectly shows the experimental warning
      env: TEST=true
