version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
 - ljharb/travis-ci:node/coverage.yml
matrix:
  allow_failures:
    - env: COVERAGE=true # temporarily allow this to fail
  include:
    - node_js: "12.16.0" # this node version incorrectly shows the experimental warning
      env: TEST=true
