version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "6.1" ] || [ "${TRAVIS_NODE_VERSION}" = "6.0" ] || [ "${TRAVIS_NODE_VERSION}" = "5.12" ] || [ "${TRAVIS_NODE_VERSION}" = "5.11" ] || [ "${TRAVIS_NODE_VERSION}" = "5.10" ] || [ "${TRAVIS_NODE_VERSION}" = "4.9" ] || [ "${TRAVIS_NODE_VERSION}" = "4.8" ] || [ "${TRAVIS_NODE_VERSION}" = "4.7" ]; then nvm install --latest-npm 6; fi;'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "9.0" ] || [ "${TRAVIS_NODE_VERSION}" = "9.1" ] || [ "${TRAVIS_NODE_VERSION}" = "9.2" ]; then nvm install --latest-npm 10; fi;'
after_install:
  - 'nvm use "${TRAVIS_NODE_VERSION}"'
matrix:
  exclude:
    - node_js: "12.17"
      env: TEST=true ALLOW_FAILURE=true
  include:
    - node_js: "12.17" # first 12.x with ESM
      env: TEST=true
    - node_js: "12.16.0" # this node version incorrectly shows the experimental warning
      env: TEST=true
